
modalities: ["rna", "dnam", "wsi", "mri"]
defaults: 
  - rna_model: rna_mae
  - mri_model: mri_mae_model
  - dnam_model: dna_mae
  - wsi_model: wsi_mae

hidden_size: 256
is_projection: False
attention_probs_dropout_prob: 0.0
decoder_hidden_size: 256
decoder_intermediate_size: 512
decoder_num_attention_heads: 4
decoder_num_hidden_layers: 3
hidden_act: "gelu"
hidden_dropout_prob: 0.0
initializer_range: 0.02
intermediate_size: 1024
layer_norm_eps: 1e-12
mask_ratio: 0.5
model_type: "vit_mae"
norm_pix_loss: false
num_attention_heads: 4
num_channels: 1
num_hidden_layers: 6
qkv_bias: true
patch_size: 512
is_load_pretrained: false
pretrained_model_name: ""
pretrained_model_path: ""
postprocessing: True
output_dim: 20
contrastive_loss: false

encoder_fusion_strategy: "identity"

encoder_fusion_depth: 1
encoder_fusion_dim: 256
encoder_fusion_nhead: 4
encoder_fusion_dim_feedforward: 1024
encoder_fusion_dropout: 0.1

fusion_strategy: "mask_attention"
fusion_depth: 1
fusion_dim: 256
fusion_nhead: 4
fusion_dim_feedforward: 1024
fusion_dropout: 0.1
