defaults: 
    - model: wsi_mae_model_pretrain
    - base: wsi_mae_model
    - data: wsi_mae
base:
    experiment_name: "unimodal_wsi_800_mae_2conv_surv_1e_2_with_pyramid"
    n_epochs: 50
    n_intervals: 20
    random_seed: 1380

    optimizer:
        name: "AdamW"
        params:
            lr: 1e-2 #1e-3
            weight_decay: 1e-2
    
    scheduler: 
        name: "CosineAnnealingLR"
        params:
            eta_min: 5e-6


    type: "unimodal"
    strategy: "survival" # mae, survival
    modalities: ["wsi"] #rna, mri
    splits: 5
    data_path: "/home/a.beliaeva/mtcp/src/data/dataset_glioma_with_treatment.csv"
    root_path: "../"
    save_path : "/home/a.beliaeva/mtcp/src/outputs/models/unimodal_wsi_800_mae_2conv_surv/"
    device: "cuda:3"  # Указываем, что основное устройство - GPU 2
    available_gpus: [3]  # Указываем, какие GPU можно использовать
    remove_nan_column: 'WSI_initial'
    batch_size: 16

    log:
        logging: True
        wandb_project: "cancer_mtcp"
        wandb_run_name: ${base.experiment_name}
