defaults: 
    - model: wsi_mae_model
    - base: wsi_mae_model
    - data: wsi_mae
base:
    experiment_name: "wsi mae"
    n_epochs: 50
    n_intervals: 20
    random_seed: 1380

    optimizer:
        name: "AdamW"
        params:
            lr: 1e-3
            weight_decay: 1e-2
    
    scheduler: 
        name: "CosineAnnealingLR"
        params:
            eta_min: 5e-6


    type: "unimodal"
    strategy: "mae" # mae, survival
    modalities: ["wsi"] #rna, mri
    splits: 5
    data_path: "src/data/updated_utf8.csv"
    root_path: "../"
    save_path : "outputs/models/main_mae/"
    device: "cuda:1"  # Указываем, что основное устройство - GPU 2
    available_gpus:  [0, 1, 2, 3, 4]  # Указываем, какие GPU можно использовать
    remove_nan_column: 'WSI_initial'
    batch_size: 8

    log:
        logging: True
        wandb_project: "cancer_mtcp"
        wandb_run_name: ${base.experiment_name}
