experiment_name: "cnv_base_without_clusters_survival"
n_epochs: 50
n_intervals: 20
random_seed: 1380

optimizer:
    name: "Adam"
    params:
        lr: 1e-3 # 2e-5
        weight_decay: 1e-2

scheduler: 
    name: "CosineAnnealingLR"
    params:
        eta_min: 5e-6


type: "unimodal"
strategy: "survival" # mae, survival
modalities: ["cnv"]
architecture: "MAE"
splits: 5
project_ids: ["GBM", "LGG"]
data_path: "src/data/dataset_full_tcga_with_dna_cnv_balanced.csv"
root_path: "../"
save_path : "outputs/models/"
device: "cuda:2"
remove_nan_column: 'CNV'
batch_size: 24

log:
    logging: True
    wandb_project: "cancer_mtcp"
    wandb_run_name: "test_cnv_dna"