experiment_name: "dna_without_clusters_mae_survival_predict"
n_epochs: 50
n_intervals: 20
random_seed: 1380

optimizer:
    name: "Adam"
    params:
        lr: 1e-3 # 2e-5
        weight_decay: 1e-2
    
scheduler: 
    name: "CosineAnnealingLR"
    params:
        eta_min: 5e-6

type: "unimodal"
strategy: "survival" # mae, survival
modalities: ["dnam"]
architecture: "MAE"
splits: 5
data_path: "src/data/dataset.csv"
root_path: "../"
save_path : "outputs/models/"
device: "cuda:1"
remove_nan_column: 'DNAm'
batch_size: 24

log:
    logging: True
    wandb_project: "cancer_mtcp"
    wandb_run_name: "test_dnam_encoder"
