experiment_name: "multimodal_rna_dnam_balanced_pretrained_dropout_256_clusters_survival"
n_epochs: 50
n_intervals: 20
random_seed: 1380

optimizer:
    name: "Adam"
    params:
        lr: 1e-3 # 1e-3
        weight_decay: 1e-2
    
scheduler: 
    name: "CosineAnnealingLR"
    params:
        eta_min: 5e-6

type: "multimodal"
strategy: "survival" # mae, survival

modalities: ["rna", "dnam"]

multimodal_intersection_test: true
architecture: "MAE"
splits: 5
save_path : "outputs/models/"
project_ids: ["KIRC"]
data_path: "src/data/dataset_full_tcga_all_balanced.csv"
rna_dataset_path: "src/data/rna_dataset_full_tcga.csv"
device: "cuda:1"
available_gpus:  [1, 3]  # Указываем, какие GPU можно использовать
remove_nan_column: 'RNA'
batch_size: 24

log:
    logging: True
    wandb_project: "cancer_mtcp"
    wandb_run_name: "test_multimodal_mae"

# early_stopping:
#     early_stopper:
#         patience: 7
#         eps: 0
#         smoothing: "running_average"
#         smoothing_period: 5
#         direction: "min"
#     value_to_track: "task_loss"