experiment_name: "multimodal_test_without_clusters_quantile_mae_dna_rna"
n_epochs: 50
n_intervals: 20
random_seed: 1380

optimizer:
    name: "Adam"
    params:
        lr: 1e-3 # 2e-5
        weight_decay: 1e-2
    
scheduler: 
    name: "CosineAnnealingLR"
    params:
        eta_min: 5e-6

type: "multimodal"
strategy: "mae" # mae, survival
modalities: ["rna", "dnam"]
multimodal_intersection_test: true
architecture: "MAE"
splits: 5
data_path: "src/data/dataset.csv"
save_path : "outputs/models/"

device: "cuda:0"
remove_nan_column: 'RNA'
batch_size: 24

log:
    logging: True
    wandb_project: "cancer_mtcp"
    wandb_run_name: "test_multimodal_rna_dna_mae"
