experiment_name: "multimodal_rna_dna_wsi_400_mae_last"
n_epochs: 400
n_intervals: 20
random_seed: 1380

optimizer:
    name: "Adam"
    params:
        lr: 1e-3 # 2e-5
        weight_decay: 1e-2
    
scheduler: 
    name: "CosineAnnealingLR"
    params:
        eta_min: 5e-6

type: "multimodal"
strategy: "mae" # mae, survival
modalities: ["rna", "dnam", "wsi"]
multimodal_intersection_test: false
architecture: "MAE"
splits: 5
data_path: "src/data/dataset.csv"
save_path : "outputs/models/"
rna_dataset_path: "src/data/rna_dataset.csv"
device: "cuda:2"
available_gpus:  [0, 1, 2]
remove_nan_column: 'RNA'
batch_size: 24

log:
    logging: True
    wandb_project: "cancer_mtcp"
    wandb_run_name: "multimodal_rna_dna_wsi_400_mae_last"

profiling:
    sort_by_keyword: self_cuda_time_total #by which parameter profiler output should be sorted
    row_limit: 10 #how many rows should be in profiler output
    is_print: True
